<?php

/**
 * @file
 * bos365_latest_sponsor.module
 *
 * Custom functionality for the Boston O365 User Group.
 */

use Drupal\Core\Database\Query\AlterableInterface;

/**
 * Order sponsors by the related session.
 */
function bos365_query_home_sponsors_alter(AlterableInterface $query) {
  $query->join('node__field_date', 'nfd', "field_sponsor_node_field_data.nid = nfd.entity_id AND nfd.deleted = '0'");
  $query->orderBy('nfd.field_date_value', 'DESC');
}